#define DEBUG false

#define MAX_REMINDERS 64
#define BUF_LEN 32
#define LONG_CLICK 500
  
#define SNOOZE_DEFAULT TEN_MIN
#define SNOOZE_LABEL_MAX_SIZE 64

// Memory indexes.
#define WAKEUP_ID_KEY 0
#define REMINDERS_KEY 1
  
#define REMINDERS_DEFAULT_START_KEY 500
#define REMINDERS_START_KEY_MARGIN  50
#define REMINDERS_COUNT_KEY         2
#define REMINDERS_START_KEY         3